version: '3'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DOCKER_DB_PORT}:5432"
  cache:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - cache:/var/lib/redis/data
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
  storage:
    build:
      context: ./src
    ports:
      - "${DOCKER_API_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 5
      && alembic upgrade head
      && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
volumes:
  db:
  cache: