version: '3'
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  cache:
    image: redis:6.2-alpine
    restart: always
    volumes: 
      - cache:/var/lib/redis/data
    env_file:
      - .env
  storage:
    build:
      context: ./src
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: >
      sh -c "sleep 5
      && alembic upgrade head
      && python -m gunicorn --name url_service -k uvicorn.workers.UvicornWorker -w 2 -b 0.0.0.0:8000 main:app"
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "${DOCKER_API_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - storage
volumes:
  db:
  cache: